//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace VetMedData.NET
{
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class VMDPID_Raw
    {

        private VMD_PIDProductsCurrentAuthorisedProducts[] currentAuthorisedProductsField;

        private VMD_PIDProductsSuspendedProducts[] suspendedProductsField;

        private VMD_PIDProductsExpiredProducts[] expiredProductsField;

        private VMD_PIDProductsHomeopathicProducts[] homeopathicProductsField;

        /// <remarks/>
        [XmlElement("CurrentAuthorisedProducts")]
        public VMD_PIDProductsCurrentAuthorisedProducts[] CurrentAuthorisedProducts
        {
            get
            {
                return this.currentAuthorisedProductsField;
            }
            set
            {
                this.currentAuthorisedProductsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("SuspendedProducts")]
        public VMD_PIDProductsSuspendedProducts[] SuspendedProducts
        {
            get
            {
                return this.suspendedProductsField;
            }
            set
            {
                this.suspendedProductsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ExpiredProducts")]
        public VMD_PIDProductsExpiredProducts[] ExpiredProducts
        {
            get
            {
                return this.expiredProductsField;
            }
            set
            {
                this.expiredProductsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("HomeopathicProducts")]
        public VMD_PIDProductsHomeopathicProducts[] HomeopathicProducts
        {
            get
            {
                return this.homeopathicProductsField;
            }
            set
            {
                this.homeopathicProductsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class VMD_PIDProductsCurrentAuthorisedProducts
    {

        private string nameField;

        private string mAHolderField;

        private string distributorsField;

        private string vMNoField;

        private System.DateTime dateOfIssueField;

        private string authorisationRouteField;

        private string activeSubstancesField;

        private char controlledDrugField;

        private string targetSpeciesField;

        private string distributionCategoryField;

        private string pharmaceuticalFormField;

        private string therapeuticGroupField;

        private string sPC_LinkField;

        private string uKPAR_LinkField;

        private string pAAR_LinkField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string MAHolder
        {
            get
            {
                return this.mAHolderField;
            }
            set
            {
                this.mAHolderField = value;
            }
        }

        /// <remarks/>
        public string Distributors
        {
            get
            {
                return this.distributorsField;
            }
            set
            {
                this.distributorsField = value;
            }
        }

        /// <remarks/>
        public string VMNo
        {
            get
            {
                return this.vMNoField;
            }
            set
            {
                this.vMNoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public System.DateTime DateOfIssue
        {
            get
            {
                return this.dateOfIssueField;
            }
            set
            {
                this.dateOfIssueField = value;
            }
        }

        /// <remarks/>
        public string AuthorisationRoute
        {
            get
            {
                return this.authorisationRouteField;
            }
            set
            {
                this.authorisationRouteField = value;
            }
        }

        /// <remarks/>
        public string ActiveSubstances
        {
            get
            {
                return this.activeSubstancesField;
            }
            set
            {
                this.activeSubstancesField = value;
            }
        }

        /// <remarks/>
        public char ControlledDrug
        {
            get
            {
                return this.controlledDrugField;
            }
            set
            {
                this.controlledDrugField = value;
            }
        }

        /// <remarks/>
        public string TargetSpecies
        {
            get
            {
                return this.targetSpeciesField;
            }
            set
            {
                this.targetSpeciesField = value;
            }
        }

        /// <remarks/>
        public string DistributionCategory
        {
            get
            {
                return this.distributionCategoryField;
            }
            set
            {
                this.distributionCategoryField = value;
            }
        }

        /// <remarks/>
        public string PharmaceuticalForm
        {
            get
            {
                return this.pharmaceuticalFormField;
            }
            set
            {
                this.pharmaceuticalFormField = value;
            }
        }

        /// <remarks/>
        public string TherapeuticGroup
        {
            get
            {
                return this.therapeuticGroupField;
            }
            set
            {
                this.therapeuticGroupField = value;
            }
        }

        /// <remarks/>
        public string SPC_Link
        {
            get
            {
                return this.sPC_LinkField;
            }
            set
            {
                this.sPC_LinkField = value;
            }
        }

        /// <remarks/>
        public string UKPAR_Link
        {
            get
            {
                return this.uKPAR_LinkField;
            }
            set
            {
                this.uKPAR_LinkField = value;
            }
        }

        /// <remarks/>
        public string PAAR_Link
        {
            get
            {
                return this.pAAR_LinkField;
            }
            set
            {
                this.pAAR_LinkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class VMD_PIDProductsSuspendedProducts
    {

        private string nameField;

        private string mAHolderField;

        private string vMNoField;

        private System.DateTime dateOfIssueField;

        private string authorisationRouteField;

        private string activeSubstancesField;

        private string controlledDrugField;

        private string targetSpeciesField;

        private string distributionCategoryField;

        private System.DateTime dateOfSuspensionField;

        private string pharmaceuticalFormField;

        private string therapeuticGroupField;

        private string sPC_LinkField;

        private string uKPAR_LinkField;

        private string pAAR_LinkField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string MAHolder
        {
            get
            {
                return this.mAHolderField;
            }
            set
            {
                this.mAHolderField = value;
            }
        }

        /// <remarks/>
        public string VMNo
        {
            get
            {
                return this.vMNoField;
            }
            set
            {
                this.vMNoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public System.DateTime DateOfIssue
        {
            get
            {
                return this.dateOfIssueField;
            }
            set
            {
                this.dateOfIssueField = value;
            }
        }

        /// <remarks/>
        public string AuthorisationRoute
        {
            get
            {
                return this.authorisationRouteField;
            }
            set
            {
                this.authorisationRouteField = value;
            }
        }

        /// <remarks/>
        public string ActiveSubstances
        {
            get
            {
                return this.activeSubstancesField;
            }
            set
            {
                this.activeSubstancesField = value;
            }
        }

        /// <remarks/>
        public string ControlledDrug
        {
            get
            {
                return this.controlledDrugField;
            }
            set
            {
                this.controlledDrugField = value;
            }
        }

        /// <remarks/>
        public string TargetSpecies
        {
            get
            {
                return this.targetSpeciesField;
            }
            set
            {
                this.targetSpeciesField = value;
            }
        }

        /// <remarks/>
        public string DistributionCategory
        {
            get
            {
                return this.distributionCategoryField;
            }
            set
            {
                this.distributionCategoryField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public System.DateTime DateOfSuspension
        {
            get
            {
                return this.dateOfSuspensionField;
            }
            set
            {
                this.dateOfSuspensionField = value;
            }
        }

        /// <remarks/>
        public string PharmaceuticalForm
        {
            get
            {
                return this.pharmaceuticalFormField;
            }
            set
            {
                this.pharmaceuticalFormField = value;
            }
        }

        /// <remarks/>
        public string TherapeuticGroup
        {
            get
            {
                return this.therapeuticGroupField;
            }
            set
            {
                this.therapeuticGroupField = value;
            }
        }

        /// <remarks/>
        public string SPC_Link
        {
            get
            {
                return this.sPC_LinkField;
            }
            set
            {
                this.sPC_LinkField = value;
            }
        }

        /// <remarks/>
        public string UKPAR_Link
        {
            get
            {
                return this.uKPAR_LinkField;
            }
            set
            {
                this.uKPAR_LinkField = value;
            }
        }

        /// <remarks/>
        public string PAAR_Link
        {
            get
            {
                return this.pAAR_LinkField;
            }
            set
            {
                this.pAAR_LinkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class VMD_PIDProductsExpiredProducts
    {

        private string nameField;

        private string mAHolderField;

        private string vMNoField;

        private System.DateTime dateOfExpirationField;

        private string authorisationRouteField;

        private string activeSubstancesField;

        private string sPC_LinkField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string MAHolder
        {
            get
            {
                return this.mAHolderField;
            }
            set
            {
                this.mAHolderField = value;
            }
        }

        /// <remarks/>
        public string VMNo
        {
            get
            {
                return this.vMNoField;
            }
            set
            {
                this.vMNoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public System.DateTime DateOfExpiration
        {
            get
            {
                return this.dateOfExpirationField;
            }
            set
            {
                this.dateOfExpirationField = value;
            }
        }

        /// <remarks/>
        public string AuthorisationRoute
        {
            get
            {
                return this.authorisationRouteField;
            }
            set
            {
                this.authorisationRouteField = value;
            }
        }

        /// <remarks/>
        public string ActiveSubstances
        {
            get
            {
                return this.activeSubstancesField;
            }
            set
            {
                this.activeSubstancesField = value;
            }
        }

        /// <remarks/>
        public string SPC_Link
        {
            get
            {
                return this.sPC_LinkField;
            }
            set
            {
                this.sPC_LinkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class VMD_PIDProductsHomeopathicProducts
    {

        private string nameField;

        private string mAHolderField;

        private string vMNoField;

        private System.DateTime dateOfIssueField;

        private string authorisationRouteField;

        private string activeSubstancesField;

        private string controlledDrugField;

        private string targetSpeciesField;

        private string distributionCategoryField;

        private string pharmaceuticalFormField;

        private string therapeuticGroupField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string MAHolder
        {
            get
            {
                return this.mAHolderField;
            }
            set
            {
                this.mAHolderField = value;
            }
        }

        /// <remarks/>
        public string VMNo
        {
            get
            {
                return this.vMNoField;
            }
            set
            {
                this.vMNoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "date")]
        public System.DateTime DateOfIssue
        {
            get
            {
                return this.dateOfIssueField;
            }
            set
            {
                this.dateOfIssueField = value;
            }
        }

        /// <remarks/>
        public string AuthorisationRoute
        {
            get
            {
                return this.authorisationRouteField;
            }
            set
            {
                this.authorisationRouteField = value;
            }
        }

        /// <remarks/>
        public string ActiveSubstances
        {
            get
            {
                return this.activeSubstancesField;
            }
            set
            {
                this.activeSubstancesField = value;
            }
        }

        /// <remarks/>
        public string ControlledDrug
        {
            get
            {
                return this.controlledDrugField;
            }
            set
            {
                this.controlledDrugField = value;
            }
        }

        /// <remarks/>
        public string TargetSpecies
        {
            get
            {
                return this.targetSpeciesField;
            }
            set
            {
                this.targetSpeciesField = value;
            }
        }

        /// <remarks/>
        public string DistributionCategory
        {
            get
            {
                return this.distributionCategoryField;
            }
            set
            {
                this.distributionCategoryField = value;
            }
        }

        /// <remarks/>
        public string PharmaceuticalForm
        {
            get
            {
                return this.pharmaceuticalFormField;
            }
            set
            {
                this.pharmaceuticalFormField = value;
            }
        }

        /// <remarks/>
        public string TherapeuticGroup
        {
            get
            {
                return this.therapeuticGroupField;
            }
            set
            {
                this.therapeuticGroupField = value;
            }
        }
    }
}