### YamlMime:ManagedReference
items:
- uid: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig
  commentId: T:VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig
  id: DefaultProductNameMetricConfig
  parent: VetMedData.NET.ProductMatching
  children:
  - VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor
  langs:
  - csharp
  - vb
  name: DefaultProductNameMetricConfig
  nameWithType: DefaultProductNameMetricConfig
  fullName: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig
  type: Class
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductNameMetricConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: DefaultProductNameMetricConfig
    path: ProductMatching/ProductNameMetricConfig.cs
    startLine: 41
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: 'public class DefaultProductNameMetricConfig : ProductNameMetricConfig'
    content.vb: >-
      Public Class DefaultProductNameMetricConfig
          Inherits ProductNameMetricConfig
  inheritance:
  - System.Object
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig
  inheritedMembers:
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.InnerMetric
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.NameCleaningConfig
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.Tokeniser
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.APositionalWeightingCoefficientPower
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.BPositionalWeightingCoefficientPower
  - VetMedData.NET.ProductMatching.ProductNameMetricConfig.ABCompoundPositionalWeightRatio
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor
  commentId: M:VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor
  id: '#ctor'
  parent: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig
  langs:
  - csharp
  - vb
  name: DefaultProductNameMetricConfig()
  nameWithType: DefaultProductNameMetricConfig.DefaultProductNameMetricConfig()
  fullName: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.DefaultProductNameMetricConfig()
  type: Constructor
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductNameMetricConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: .ctor
    path: ProductMatching/ProductNameMetricConfig.cs
    startLine: 43
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public DefaultProductNameMetricConfig()
    content.vb: Public Sub New
  overload: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VetMedData.NET.ProductMatching
  commentId: N:VetMedData.NET.ProductMatching
  name: VetMedData.NET.ProductMatching
  nameWithType: VetMedData.NET.ProductMatching
  fullName: VetMedData.NET.ProductMatching
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  commentId: T:VetMedData.NET.ProductMatching.ProductNameMetricConfig
  parent: VetMedData.NET.ProductMatching
  name: ProductNameMetricConfig
  nameWithType: ProductNameMetricConfig
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.InnerMetric
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.InnerMetric
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: InnerMetric
  nameWithType: ProductNameMetricConfig.InnerMetric
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.InnerMetric
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.NameCleaningConfig
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.NameCleaningConfig
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: NameCleaningConfig
  nameWithType: ProductNameMetricConfig.NameCleaningConfig
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.NameCleaningConfig
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.Tokeniser
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.Tokeniser
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: Tokeniser
  nameWithType: ProductNameMetricConfig.Tokeniser
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.Tokeniser
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.APositionalWeightingCoefficientPower
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.APositionalWeightingCoefficientPower
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: APositionalWeightingCoefficientPower
  nameWithType: ProductNameMetricConfig.APositionalWeightingCoefficientPower
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.APositionalWeightingCoefficientPower
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.BPositionalWeightingCoefficientPower
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.BPositionalWeightingCoefficientPower
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: BPositionalWeightingCoefficientPower
  nameWithType: ProductNameMetricConfig.BPositionalWeightingCoefficientPower
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.BPositionalWeightingCoefficientPower
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig.ABCompoundPositionalWeightRatio
  commentId: P:VetMedData.NET.ProductMatching.ProductNameMetricConfig.ABCompoundPositionalWeightRatio
  parent: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  name: ABCompoundPositionalWeightRatio
  nameWithType: ProductNameMetricConfig.ABCompoundPositionalWeightRatio
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig.ABCompoundPositionalWeightRatio
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor*
  commentId: Overload:VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.#ctor
  name: DefaultProductNameMetricConfig
  nameWithType: DefaultProductNameMetricConfig.DefaultProductNameMetricConfig
  fullName: VetMedData.NET.ProductMatching.DefaultProductNameMetricConfig.DefaultProductNameMetricConfig
