### YamlMime:ManagedReference
items:
- uid: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig
  commentId: T:VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig
  id: DefaultMatchNameCleaningConfig
  parent: VetMedData.NET.ProductMatching
  children:
  - VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor
  langs:
  - csharp
  - vb
  name: DefaultMatchNameCleaningConfig
  nameWithType: DefaultMatchNameCleaningConfig
  fullName: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig
  type: Class
  source:
    remote:
      path: VetMedData.NET/ProductMatching/NameCleaningConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: DefaultMatchNameCleaningConfig
    path: ProductMatching/NameCleaningConfig.cs
    startLine: 6
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  summary: "\nDefault set of rules to agressively clean medicine names for\nname matching.\n"
  example: []
  syntax:
    content: 'public class DefaultMatchNameCleaningConfig : NameCleaningConfig'
    content.vb: >-
      Public Class DefaultMatchNameCleaningConfig
          Inherits NameCleaningConfig
  inheritance:
  - System.Object
  - VetMedData.NET.ProductMatching.NameCleaningConfig
  inheritedMembers:
  - VetMedData.NET.ProductMatching.NameCleaningConfig.Lowercase
  - VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveBracketedTerms
  - VetMedData.NET.ProductMatching.NameCleaningConfig.CharsToRemove
  - VetMedData.NET.ProductMatching.NameCleaningConfig.TermsToRemove
  - VetMedData.NET.ProductMatching.NameCleaningConfig.PatternsToRemove
  - VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveLeadingMultiplierTerms
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor
  commentId: M:VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor
  id: '#ctor'
  parent: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig
  langs:
  - csharp
  - vb
  name: DefaultMatchNameCleaningConfig()
  nameWithType: DefaultMatchNameCleaningConfig.DefaultMatchNameCleaningConfig()
  fullName: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.DefaultMatchNameCleaningConfig()
  type: Constructor
  source:
    remote:
      path: VetMedData.NET/ProductMatching/NameCleaningConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: .ctor
    path: ProductMatching/NameCleaningConfig.cs
    startLine: 8
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public DefaultMatchNameCleaningConfig()
    content.vb: Public Sub New
  overload: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: VetMedData.NET.ProductMatching
  commentId: N:VetMedData.NET.ProductMatching
  name: VetMedData.NET.ProductMatching
  nameWithType: VetMedData.NET.ProductMatching
  fullName: VetMedData.NET.ProductMatching
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig
  commentId: T:VetMedData.NET.ProductMatching.NameCleaningConfig
  parent: VetMedData.NET.ProductMatching
  name: NameCleaningConfig
  nameWithType: NameCleaningConfig
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.Lowercase
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.Lowercase
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: Lowercase
  nameWithType: NameCleaningConfig.Lowercase
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.Lowercase
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveBracketedTerms
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveBracketedTerms
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: RemoveBracketedTerms
  nameWithType: NameCleaningConfig.RemoveBracketedTerms
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveBracketedTerms
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.CharsToRemove
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.CharsToRemove
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: CharsToRemove
  nameWithType: NameCleaningConfig.CharsToRemove
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.CharsToRemove
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.TermsToRemove
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.TermsToRemove
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: TermsToRemove
  nameWithType: NameCleaningConfig.TermsToRemove
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.TermsToRemove
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.PatternsToRemove
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.PatternsToRemove
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: PatternsToRemove
  nameWithType: NameCleaningConfig.PatternsToRemove
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.PatternsToRemove
- uid: VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveLeadingMultiplierTerms
  commentId: P:VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveLeadingMultiplierTerms
  parent: VetMedData.NET.ProductMatching.NameCleaningConfig
  name: RemoveLeadingMultiplierTerms
  nameWithType: NameCleaningConfig.RemoveLeadingMultiplierTerms
  fullName: VetMedData.NET.ProductMatching.NameCleaningConfig.RemoveLeadingMultiplierTerms
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor*
  commentId: Overload:VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.#ctor
  name: DefaultMatchNameCleaningConfig
  nameWithType: DefaultMatchNameCleaningConfig.DefaultMatchNameCleaningConfig
  fullName: VetMedData.NET.ProductMatching.DefaultMatchNameCleaningConfig.DefaultMatchNameCleaningConfig
