### YamlMime:ManagedReference
items:
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig
  commentId: T:VetMedData.NET.ProductMatching.ProductMatchConfig
  id: ProductMatchConfig
  parent: VetMedData.NET.ProductMatching
  children:
  - VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
  - VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
  - VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
  langs:
  - csharp
  - vb
  name: ProductMatchConfig
  nameWithType: ProductMatchConfig
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig
  type: Class
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductMatchConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: ProductMatchConfig
    path: ProductMatching/ProductMatchConfig.cs
    startLine: 2
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public abstract class ProductMatchConfig
    content.vb: Public MustInherit Class ProductMatchConfig
  inheritance:
  - System.Object
  derivedClasses:
  - VetMedData.NET.ProductMatching.DefaultProductMatchConfig
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
  commentId: P:VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
  id: NameMetricConfig
  parent: VetMedData.NET.ProductMatching.ProductMatchConfig
  langs:
  - csharp
  - vb
  name: NameMetricConfig
  nameWithType: ProductMatchConfig.NameMetricConfig
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
  type: Property
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductMatchConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: NameMetricConfig
    path: ProductMatching/ProductMatchConfig.cs
    startLine: 4
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public ProductNameMetricConfig NameMetricConfig { get; set; }
    parameters: []
    return:
      type: VetMedData.NET.ProductMatching.ProductNameMetricConfig
    content.vb: Public Property NameMetricConfig As ProductNameMetricConfig
  overload: VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
  commentId: P:VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
  id: Disambiguator
  parent: VetMedData.NET.ProductMatching.ProductMatchConfig
  langs:
  - csharp
  - vb
  name: Disambiguator
  nameWithType: ProductMatchConfig.Disambiguator
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
  type: Property
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductMatchConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: Disambiguator
    path: ProductMatching/ProductMatchConfig.cs
    startLine: 5
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public IProductMatchDisambiguator Disambiguator { get; set; }
    parameters: []
    return:
      type: VetMedData.NET.ProductMatching.IProductMatchDisambiguator
    content.vb: Public Property Disambiguator As IProductMatchDisambiguator
  overload: VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
  commentId: P:VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
  id: DisambiguationCandidiateFilter
  parent: VetMedData.NET.ProductMatching.ProductMatchConfig
  langs:
  - csharp
  - vb
  name: DisambiguationCandidiateFilter
  nameWithType: ProductMatchConfig.DisambiguationCandidiateFilter
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
  type: Property
  source:
    remote:
      path: VetMedData.NET/ProductMatching/ProductMatchConfig.cs
      branch: master
      repo: https://github.com/Jongmassey/VetMedData.NET.git
    id: DisambiguationCandidiateFilter
    path: ProductMatching/ProductMatchConfig.cs
    startLine: 6
  assemblies:
  - VetMedData.NET
  namespace: VetMedData.NET.ProductMatching
  syntax:
    content: public IProductMatchResultFilter DisambiguationCandidiateFilter { get; set; }
    parameters: []
    return:
      type: VetMedData.NET.ProductMatching.IProductMatchResultFilter
    content.vb: Public Property DisambiguationCandidiateFilter As IProductMatchResultFilter
  overload: VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: VetMedData.NET.ProductMatching
  commentId: N:VetMedData.NET.ProductMatching
  name: VetMedData.NET.ProductMatching
  nameWithType: VetMedData.NET.ProductMatching
  fullName: VetMedData.NET.ProductMatching
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig*
  commentId: Overload:VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
  name: NameMetricConfig
  nameWithType: ProductMatchConfig.NameMetricConfig
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.NameMetricConfig
- uid: VetMedData.NET.ProductMatching.ProductNameMetricConfig
  commentId: T:VetMedData.NET.ProductMatching.ProductNameMetricConfig
  parent: VetMedData.NET.ProductMatching
  name: ProductNameMetricConfig
  nameWithType: ProductNameMetricConfig
  fullName: VetMedData.NET.ProductMatching.ProductNameMetricConfig
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator*
  commentId: Overload:VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
  name: Disambiguator
  nameWithType: ProductMatchConfig.Disambiguator
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.Disambiguator
- uid: VetMedData.NET.ProductMatching.IProductMatchDisambiguator
  commentId: T:VetMedData.NET.ProductMatching.IProductMatchDisambiguator
  parent: VetMedData.NET.ProductMatching
  name: IProductMatchDisambiguator
  nameWithType: IProductMatchDisambiguator
  fullName: VetMedData.NET.ProductMatching.IProductMatchDisambiguator
- uid: VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter*
  commentId: Overload:VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
  name: DisambiguationCandidiateFilter
  nameWithType: ProductMatchConfig.DisambiguationCandidiateFilter
  fullName: VetMedData.NET.ProductMatching.ProductMatchConfig.DisambiguationCandidiateFilter
- uid: VetMedData.NET.ProductMatching.IProductMatchResultFilter
  commentId: T:VetMedData.NET.ProductMatching.IProductMatchResultFilter
  parent: VetMedData.NET.ProductMatching
  name: IProductMatchResultFilter
  nameWithType: IProductMatchResultFilter
  fullName: VetMedData.NET.ProductMatching.IProductMatchResultFilter
